export const hiraganaVocab = [
    // --- GREETINGS & ESSENTIALS ---
    { kana: 'おはよう', romaji: 'ohayou', english: 'Good morning' },
    { kana: 'こんにちは', romaji: 'konnichiwa', english: 'Good afternoon' },
    { kana: 'ありがとう', romaji: 'arigatou', english: 'Thank you' },
    { kana: 'はい', romaji: 'hai', english: 'Yes' },
    { kana: 'いいえ', romaji: 'iie', english: 'No' },
    { kana: 'すみません', romaji: 'sumimasen', english: 'Excuse me / Sorry' },
    { kana: 'おねがい', romaji: 'onegai', english: 'Please' },
    
    // --- PEOPLE & FAMILY ---
    { kana: 'わたし', romaji: 'watashi', english: 'I / Me' },
    { kana: 'あなた', romaji: 'anata', english: 'You' },
    { kana: 'ひと', romaji: 'hito', english: 'Person' },
    { kana: 'ともだち', romaji: 'tomodachi', english: 'Friend' },
    { kana: 'かぞく', romaji: 'kazoku', english: 'Family' },
    { kana: 'こども', romaji: 'kodomo', english: 'Child' },

    // --- FOOD & DRINK ---
    { kana: 'みず', romaji: 'mizu', english: 'Water' },
    { kana: 'おちゃ', romaji: 'ocha', english: 'Tea' },
    { kana: 'ごはん', romaji: 'gohan', english: 'Rice / Meal' },
    { kana: 'にく', romaji: 'niku', english: 'Meat' },
    { kana: 'さかな', romaji: 'sakana', english: 'Fish' },
    { kana: 'やさい', romaji: 'yasai', english: 'Vegetable' },
    { kana: 'たまご', romaji: 'tamago', english: 'Egg' },
    { kana: 'りんご', romaji: 'ringo', english: 'Apple' },

    // --- DAILY OBJECTS ---
    { kana: 'ほん', romaji: 'hon', english: 'Book' },
    { kana: 'くるま', romaji: 'kuruma', english: 'Car' },
    { kana: 'いえ', romaji: 'ie', english: 'House' },
    { kana: 'かさ', romaji: 'kasa', english: 'Umbrella' },
    { kana: 'かね', romaji: 'kane', english: 'Money' },
    { kana: 'でんわ', romaji: 'denwa', english: 'Phone' },
    { kana: 'かばん', romaji: 'kaban', english: 'Bag' },
    { kana: 'くつ', romaji: 'kutsu', english: 'Shoes' },

    // --- TIME & NATURE ---
    { kana: 'いま', romaji: 'ima', english: 'Now' },
    { kana: 'きょう', romaji: 'kyou', english: 'Today' },
    { kana: 'あした', romaji: 'ashita', english: 'Tomorrow' },
    { kana: 'あさ', romaji: 'asa', english: 'Morning' },
    { kana: 'よる', romaji: 'yoru', english: 'Night' },
    { kana: 'そら', romaji: 'sora', english: 'Sky' },
    { kana: 'あめ', romaji: 'ame', english: 'Rain' },
    { kana: 'やま', romaji: 'yama', english: 'Mountain' },
    { kana: 'かわ', romaji: 'kawa', english: 'River' },

    // --- ADJECTIVES (PHYSICAL & ABSTRACT) ---
    { kana: 'おおきい', romaji: 'ookii', english: 'Big' },
    { kana: 'ちいさい', romaji: 'chiisai', english: 'Small' },
    { kana: 'たかい', romaji: 'takai', english: 'High / Expensive' },
    { kana: 'ひくい', romaji: 'hikui', english: 'Low' },
    { kana: 'あたらしい', romaji: 'atarashii', english: 'New' },
    { kana: 'ふるい', romaji: 'furui', english: 'Old' },
    { kana: 'いい', romaji: 'ii', english: 'Good' },
    { kana: 'わるい', romaji: 'warui', english: 'Bad' },
    { kana: 'あつい', romaji: 'atsui', english: 'Hot' },
    { kana: 'さむい', romaji: 'samui', english: 'Cold (Weather)' },
    { kana: 'つめたい', romaji: 'tsumetai', english: 'Cold (To touch)' },
    { kana: 'むずかしい', romaji: 'muzukashii', english: 'Difficult' },
    { kana: 'やさしい', romaji: 'yasashii', english: 'Easy / Kind' },
    { kana: 'おいしい', romaji: 'oishii', english: 'Delicious' },
    { kana: 'まずい', romaji: 'mazui', english: 'Bad tasting' },
    { kana: 'いそがしい', romaji: 'isogashii', english: 'Busy' },
    { kana: 'たのしい', romaji: 'tanoshii', english: 'Fun' },
    { kana: 'あぶない', romaji: 'abunai', english: 'Dangerous' },

    // --- COLORS ---
    { kana: 'しろい', romaji: 'shiroi', english: 'White' },
    { kana: 'くろい', romaji: 'kuroi', english: 'Black' },
    { kana: 'あかい', romaji: 'akai', english: 'Red' },
    { kana: 'あおい', romaji: 'aoi', english: 'Blue' },
    { kana: 'きいろい', romaji: 'kiiroi', english: 'Yellow' },
    { kana: 'ちゃいろ', romaji: 'chairo', english: 'Brown' },
    { kana: 'みどり', romaji: 'midori', english: 'Green' },
    { kana: 'むらさき', romaji: 'murasaki', english: 'Purple' },

    // --- BODY PARTS ---
    { kana: 'あたま', romaji: 'atama', english: 'Head' },
    { kana: 'かお', romaji: 'kao', english: 'Face' },
    { kana: 'め', romaji: 'me', english: 'Eye' },
    { kana: 'みみ', romaji: 'mimi', english: 'Ear' },
    { kana: 'はな', romaji: 'hana', english: 'Nose' },
    { kana: 'くち', romaji: 'kuchi', english: 'Mouth' },
    { kana: 'は', romaji: 'ha', english: 'Tooth' },
    { kana: 'て', romaji: 'te', english: 'Hand' },
    { kana: 'あし', romaji: 'ashi', english: 'Foot / Leg' },
    { kana: 'からだ', romaji: 'karada', english: 'Body' },
    { kana: 'かみ', romaji: 'kami', english: 'Hair' },
    { kana: 'くび', romaji: 'kubi', english: 'Neck' },
    { kana: 'かた', romaji: 'kata', english: 'Shoulder' },
    { kana: 'せなか', romaji: 'senaka', english: 'Back' },
    { kana: 'おなか', romaji: 'onaka', english: 'Stomach' },

    // --- CLOTHING & ACCESSORIES ---
    { kana: 'ふく', romaji: 'fuku', english: 'Clothes' },
    { kana: 'くつした', romaji: 'kutsushita', english: 'Socks' },
    { kana: 'ぼうし', romaji: 'boushi', english: 'Hat' },
    { kana: 'めがね', romaji: 'megane', english: 'Glasses' },
    { kana: 'とけい', romaji: 'tokei', english: 'Watch / Clock' },
    { kana: 'さいふ', romaji: 'saifu', english: 'Wallet' },

    // --- HOME & FURNITURE ---
    { kana: 'へや', romaji: 'heya', english: 'Room' },
    { kana: 'まど', romaji: 'mado', english: 'Window' },
    { kana: 'つくえ', romaji: 'tsukue', english: 'Desk' },
    { kana: 'いす', romaji: 'isu', english: 'Chair' },
    { kana: 'ふとん', romaji: 'futon', english: 'Futon' },
    { kana: 'かがみ', romaji: 'kagami', english: 'Mirror' },
    { kana: 'おふろ', romaji: 'ofuro', english: 'Bath' },
    { kana: 'でんき', romaji: 'denki', english: 'Electricity / Light' },

    // --- ANIMALS ---
    { kana: 'とり', romaji: 'tori', english: 'Bird' },
    { kana: 'むし', romaji: 'mushi', english: 'Bug / Insect' },
    { kana: 'うし', romaji: 'ushi', english: 'Cow' },
    { kana: 'うま', romaji: 'uma', english: 'Horse' },
    { kana: 'ぶた', romaji: 'buta', english: 'Pig' },
    { kana: 'さる', romaji: 'saru', english: 'Monkey' },
    { kana: 'くま', romaji: 'kuma', english: 'Bear' },

    // --- CITY & PLACES ---
    { kana: 'がっこう', romaji: 'gakkou', english: 'School' },
    { kana: 'せんせい', romaji: 'sensei', english: 'Teacher' },
    { kana: 'がくせい', romaji: 'gakusei', english: 'Student' },
    { kana: 'だいがく', romaji: 'daigaku', english: 'University' },
    { kana: 'びょういん', romaji: 'byouin', english: 'Hospital' },
    { kana: 'えき', romaji: 'eki', english: 'Station' },
    { kana: 'みせ', romaji: 'mise', english: 'Shop' },
    { kana: 'ぎんこう', romaji: 'ginkou', english: 'Bank' },
    { kana: 'こうえん', romaji: 'kouen', english: 'Park' },
    { kana: 'としょかん', romaji: 'toshokan', english: 'Library' },
    { kana: 'ゆうびんきょく', romaji: 'yuubinkyoku', english: 'Post Office' },
    { kana: 'まち', romaji: 'machi', english: 'Town' },
    { kana: 'みち', romaji: 'michi', english: 'Road' },

    // --- DIRECTIONS & POSITIONS ---
    { kana: 'うえ', romaji: 'ue', english: 'Up / Above' },
    { kana: 'した', romaji: 'shita', english: 'Down / Below' },
    { kana: 'まえ', romaji: 'mae', english: 'Front' },
    { kana: 'うしろ', romaji: 'ushiro', english: 'Back / Behind' },
    { kana: 'みぎ', romaji: 'migi', english: 'Right' },
    { kana: 'ひだり', romaji: 'hidari', english: 'Left' },
    { kana: 'なか', romaji: 'naka', english: 'Inside' },
    { kana: 'そと', romaji: 'soto', english: 'Outside' },
    { kana: 'となり', romaji: 'tonari', english: 'Next to' },
    { kana: 'ちかく', romaji: 'chikaku', english: 'Nearby' },

    // --- TIME EXPANSION ---
    { kana: 'きのう', romaji: 'kinou', english: 'Yesterday' },
    { kana: 'まいにち', romaji: 'mainichi', english: 'Everyday' },
    { kana: 'しゅう', romaji: 'shuu', english: 'Week' },
    { kana: 'つき', romaji: 'tsuki', english: 'Month / Moon' },
    { kana: 'とし', romaji: 'toshi', english: 'Year' },
    { kana: 'じかん', romaji: 'jikan', english: 'Time' },
    { kana: 'ひる', romaji: 'hiru', english: 'Daytime / Noon' },
    { kana: 'ゆうがた', romaji: 'yuugata', english: 'Evening' },

    // --- VERBS ---
    { kana: 'たべる', romaji: 'taberu', english: 'To eat' },
    { kana: 'のむ', romaji: 'nomu', english: 'To drink' },
    { kana: 'いく', romaji: 'iku', english: 'To go' },
    { kana: 'くる', romaji: 'kuru', english: 'To come' },
    { kana: 'する', romaji: 'suru', english: 'To do' },
    { kana: 'みる', romaji: 'miru', english: 'To see' },
    { kana: 'きく', romaji: 'kiku', english: 'To listen / hear' },
    { kana: 'はなす', romaji: 'hanasu', english: 'To speak' },
    { kana: 'よむ', romaji: 'yomu', english: 'To read' },
    { kana: 'かく', romaji: 'kaku', english: 'To write' },
    { kana: 'かう', romaji: 'kau', english: 'To buy' },
    { kana: 'まつ', romaji: 'matsu', english: 'To wait' },
    { kana: 'あそぶ', romaji: 'asobu', english: 'To play' },
    { kana: 'およぐ', romaji: 'oyogu', english: 'To swim' },
    { kana: 'わかる', romaji: 'wakaru', english: 'To understand' },
    { kana: 'しる', romaji: 'shiru', english: 'To know' },
    { kana: 'おもう', romaji: 'omou', english: 'To think' },
    { kana: 'いう', romaji: 'iu', english: 'To say' },
    { kana: 'ある', romaji: 'aru', english: 'To exist (inanimate)' },
    { kana: 'いる', romaji: 'iru', english: 'To exist (animate)' },
    { kana: 'おわる', romaji: 'owaru', english: 'To finish' },
    { kana: 'はじまる', romaji: 'hajimaru', english: 'To begin' },
    { kana: 'あるく', romaji: 'aruku', english: 'To walk' },
    { kana: 'はしる', romaji: 'hashiru', english: 'To run' },
    { kana: 'うたう', romaji: 'utau', english: 'To sing' },
    { kana: 'ねる', romaji: 'neru', english: 'To sleep' },
    { kana: 'おきる', romaji: 'okiru', english: 'To wake up' },
    { kana: 'のる', romaji: 'noru', english: 'To ride' },
    { kana: 'おりる', romaji: 'oriru', english: 'To get off' },
    { kana: 'たつ', romaji: 'tatsu', english: 'To stand' },
    { kana: 'すわる', romaji: 'suwaru', english: 'To sit' },
    { kana: 'はたらく', romaji: 'hataraku', english: 'To work' },
    { kana: 'やすむ', romaji: 'yasumu', english: 'To rest' },
    { kana: 'つかう', romaji: 'tsukau', english: 'To use' },
    { kana: 'つくる', romaji: 'tsukuru', english: 'To make' }
    // --- PROFESSIONS & PEOPLE ---
    , { kana: 'いしゃ', romaji: 'isha', english: 'Doctor' },
    { kana: 'かんごし', romaji: 'kangoshi', english: 'Nurse' },
    { kana: 'けいさつかん', romaji: 'keisatsukan', english: 'Police Officer' },
    { kana: 'えきいん', romaji: 'ekiin', english: 'Station Attendant' },
    { kana: 'うんてんしゅ', romaji: 'untenshu', english: 'Driver' },
    { kana: 'かいしゃいん', romaji: 'kaishain', english: 'Office Worker' },
    { kana: 'てんいん', romaji: 'teniin', english: 'Store Clerk' },
    { kana: 'おとうさん', romaji: 'otousan', english: 'Father' },
    { kana: 'おかあさん', romaji: 'okaasan', english: 'Mother' },
    { kana: 'おにいさん', romaji: 'oniisan', english: 'Older Brother' },
    { kana: 'おねえさん', romaji: 'oneesan', english: 'Older Sister' },
    { kana: 'おとうと', romaji: 'otouto', english: 'Younger Brother' },
    { kana: 'いもうと', romaji: 'imouto', english: 'Younger Sister' },
    { kana: 'おじいさん', romaji: 'ojiisan', english: 'Grandfather' },
    { kana: 'おばあさん', romaji: 'obaasan', english: 'Grandmother' },
    { kana: 'おとこ', romaji: 'otoko', english: 'Man' },
    { kana: 'おんな', romaji: 'onna', english: 'Woman' },
    { kana: 'おとこのこ', romaji: 'otokonoko', english: 'Boy' },
    { kana: 'おんなのこ', romaji: 'onnanoko', english: 'Girl' },

    // --- HOUSE & EVERYDAY ITEMS ---
    { kana: 'れいぞうこ', romaji: 'reizouko', english: 'Refrigerator' },
    { kana: 'せんたくき', romaji: 'sentakuki', english: 'Washing Machine' },
    { kana: 'てれび', romaji: 'terebi', english: 'Television' },
    { kana: 'えあこん', romaji: 'eakon', english: 'Air Conditioner' },
    { kana: 'ぱそこん', romaji: 'pasokon', english: 'Computer' },
    { kana: 'けいたい', romaji: 'keitai', english: 'Mobile Phone' },
    { kana: 'といれ', romaji: 'toire', english: 'Toilet' },
    { kana: 'だいどころ', romaji: 'daidokoro', english: 'Kitchen' },
    { kana: 'にわ', romaji: 'niwa', english: 'Garden' },
    { kana: 'かべ', romaji: 'kabe', english: 'Wall' },
    { kana: 'ゆか', romaji: 'yuka', english: 'Floor' },
    { kana: 'てんじょう', romaji: 'tenjou', english: 'Ceiling' },
    { kana: 'どあ', romaji: 'doa', english: 'Door' },
    { kana: 'かぎ', romaji: 'kagi', english: 'Key' },
    { kana: 'べっど', romaji: 'beddo', english: 'Bed' },
    { kana: 'おさら', romaji: 'osara', english: 'Plate' },
    { kana: 'はし', romaji: 'hashi', english: 'Chopsticks' },
    { kana: 'こっぷ', romaji: 'koppu', english: 'Cup / Glass' },
    { kana: 'ほうちょう', romaji: 'houchou', english: 'Kitchen Knife' },
    { kana: 'たおる', romaji: 'taoru', english: 'Towel' },
    { kana: 'せっけん', romaji: 'sekken', english: 'Soap' },
    { kana: 'ごみ', romaji: 'gomi', english: 'Trash / Garbage' },

    // --- FOOD & INGREDIENTS (EXPANDED) ---
    { kana: 'ぱん', romaji: 'pan', english: 'Bread' },
    { kana: 'ぎゅうにゅう', romaji: 'gyuunyuu', english: 'Milk' },
    { kana: 'じゅーす', romaji: 'juusu', english: 'Juice' },
    { kana: 'おさけ', romaji: 'osake', english: 'Alcohol' },
    { kana: 'さとう', romaji: 'satou', english: 'Sugar' },
    { kana: 'しお', romaji: 'shio', english: 'Salt' },
    { kana: 'しょうゆ', romaji: 'shouyu', english: 'Soy Sauce' },
    { kana: 'ぎゅうにく', romaji: 'gyuuniku', english: 'Beef' },
    { kana: 'ぶたにく', romaji: 'butaniku', english: 'Pork' },
    { kana: 'とりにく', romaji: 'toriniku', english: 'Chicken' },
    { kana: 'えび', romaji: 'ebi', english: 'Shrimp' },
    { kana: 'くだもの', romaji: 'kudamono', english: 'Fruit' },
    { kana: 'みかん', romaji: 'mikan', english: 'Tangerine' },
    { kana: 'いちご', romaji: 'ichigo', english: 'Strawberry' },
    { kana: 'すいか', romaji: 'suika', english: 'Watermelon' },
    { kana: 'にんじん', romaji: 'ninjin', english: 'Carrot' },
    { kana: 'たまねぎ', romaji: 'tamanegi', english: 'Onion' },
    { kana: 'じゃがいも', romaji: 'jagaimo', english: 'Potato' },
    { kana: 'とまと', romaji: 'tomato', english: 'Tomato' },

    // --- CALENDAR, SEASONS & TIME ---
    { kana: 'げつようび', romaji: 'getsuyoubi', english: 'Monday' },
    { kana: 'かようび', romaji: 'kayoubi', english: 'Tuesday' },
    { kana: 'すいようび', romaji: 'suiyoubi', english: 'Wednesday' },
    { kana: 'もくようび', romaji: 'mokuyoubi', english: 'Thursday' },
    { kana: 'きんようび', romaji: 'kinyoubi', english: 'Friday' },
    { kana: 'どようび', romaji: 'doyoubi', english: 'Saturday' },
    { kana: 'にちようび', romaji: 'nichiyoubi', english: 'Sunday' },
    { kana: 'はる', romaji: 'haru', english: 'Spring' },
    { kana: 'なつ', romaji: 'natsu', english: 'Summer' },
    { kana: 'あき', romaji: 'aki', english: 'Autumn' },
    { kana: 'ふゆ', romaji: 'fuyu', english: 'Winter' },
    { kana: 'ごぜん', romaji: 'gozen', english: 'AM / Morning' },
    { kana: 'ごご', romaji: 'gogo', english: 'PM / Afternoon' },
    { kana: 'しゅうまつ', romaji: 'shuumatsu', english: 'Weekend' },
    { kana: 'ことし', romaji: 'kotoshi', english: 'This Year' },
    { kana: 'きょねん', romaji: 'kyonen', english: 'Last Year' },
    { kana: 'らいねん', romaji: 'rainen', english: 'Next Year' },
    { kana: 'こんげつ', romaji: 'kongetsu', english: 'This Month' },
    { kana: 'せんげつ', romaji: 'sengetsu', english: 'Last Month' },
    { kana: 'らいげつ', romaji: 'raigetsu', english: 'Next Month' },
    { kana: 'こんしゅう', romaji: 'konshuu', english: 'This Week' },
    { kana: 'せんしゅう', romaji: 'senshuu', english: 'Last Week' },
    { kana: 'らいしゅう', romaji: 'raishuu', english: 'Next Week' },

    // --- TRANSPORTATION & PLACES ---
    { kana: 'でんしゃ', romaji: 'densha', english: 'Train' },
    { kana: 'ちかてつ', romaji: 'chikatetsu', english: 'Subway' },
    { kana: 'しんかんせん', romaji: 'shinkansen', english: 'Bullet Train' },
    { kana: 'ばす', romaji: 'basu', english: 'Bus' },
    { kana: 'たくしー', romaji: 'takushii', english: 'Taxi' },
    { kana: 'ひこうき', romaji: 'hikouki', english: 'Airplane' },
    { kana: 'ふね', romaji: 'fune', english: 'Ship / Boat' },
    { kana: 'じてんしゃ', romaji: 'jitensha', english: 'Bicycle' },
    { kana: 'くうこう', romaji: 'kuukou', english: 'Airport' },
    { kana: 'えいが', romaji: 'eiga', english: 'Movie' },
    { kana: 'えいがかん', romaji: 'eigakan', english: 'Movie Theater' },
    { kana: 'びじゅつかん', romaji: 'bijutsukan', english: 'Art Museum' },
    { kana: 'はくぶつかん', romaji: 'hakubutsukan', english: 'Museum' },
    { kana: 'どうぶつえん', romaji: 'doubutsuen', english: 'Zoo' },
    { kana: 'じんじゃ', romaji: 'jinja', english: 'Shinto Shrine' },
    { kana: 'おてら', romaji: 'otera', english: 'Buddhist Temple' },
    { kana: 'かいしゃ', romaji: 'kaisha', english: 'Company' },
    { kana: 'すーぱー', romaji: 'suupaa', english: 'Supermarket' },
    { kana: 'こんびに', romaji: 'konbini', english: 'Convenience Store' },
    { kana: 'でぱーと', romaji: 'depaato', english: 'Department Store' },

    // --- ABSTRACT NOUNS ---
    { kana: 'なまえ', romaji: 'namae', english: 'Name' },
    { kana: 'しごと', romaji: 'shigoto', english: 'Job / Work' },
    { kana: 'べんきょう', romaji: 'benkyou', english: 'Study' },
    { kana: 'しつもん', romaji: 'shitsumon', english: 'Question' },
    { kana: 'こたえ', romaji: 'kotae', english: 'Answer' },
    { kana: 'もんだい', romaji: 'mondai', english: 'Problem' },
    { kana: 'いみ', romaji: 'imi', english: 'Meaning' },
    { kana: 'ことば', romaji: 'kotoba', english: 'Word / Language' },
    { kana: 'おんがく', romaji: 'ongaku', english: 'Music' }
];